name: asa
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.8
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.2
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  dio: ^5.3.3
  flutter_secure_storage: ^9.0.0
  get: ^4.6.5
  pointer_interceptor: ^0.9.3+5
  transparent_pointer: ^1.0.0
  sticky_headers: ^0.3.0+2
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logo/
    - assets/icons/

    # Fonts
    - assets/fonts/Hauora/
    - .env

  fonts:
    - family: Hauora
      fonts:
        - asset: assets/fonts/Hauora/Hauora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Hauora/Hauora-Light.ttf
          weight: 300
        - asset: assets/fonts/Hauora/Hauora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Hauora/Hauora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hauora/Hauora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Hauora/Hauora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hauora/Hauora-ExtraBold.ttf
          weight: 800
